/** Common Philippine outpatient generics. Brand names are optional and only illustrative. */
export const DRUGS: { genericName: string; brandName?: string; form: string; strength: string }[] = [
  { genericName: 'Paracetamol', brandName: 'Biogesic', form: 'Tablet', strength: '500 mg' },
  { genericName: 'Paracetamol', brandName: 'Tempra', form: 'Syrup', strength: '120 mg/5 mL' },
  { genericName: 'Ibuprofen', brandName: 'Advil', form: 'Tablet', strength: '400 mg' },
  { genericName: 'Mefenamic Acid', brandName: 'Ponstan', form: 'Capsule', strength: '500 mg' },
  { genericName: 'Naproxen Sodium', brandName: 'Flanax', form: 'Tablet', strength: '550 mg' },
  { genericName: 'Celecoxib', brandName: 'Celebrex', form: 'Capsule', strength: '200 mg' },
  { genericName: 'Amoxicillin', brandName: 'Amoxil', form: 'Capsule', strength: '500 mg' },
  { genericName: 'Amoxicillin', form: 'Suspension', strength: '250 mg/5 mL' },
  { genericName: 'Co-Amoxiclav', brandName: 'Augmentin', form: 'Tablet', strength: '625 mg' },
  { genericName: 'Cefalexin', form: 'Capsule', strength: '500 mg' },
  { genericName: 'Cefuroxime', brandName: 'Zinnat', form: 'Tablet', strength: '500 mg' },
  { genericName: 'Azithromycin', brandName: 'Zithromax', form: 'Tablet', strength: '500 mg' },
  { genericName: 'Clarithromycin', form: 'Tablet', strength: '500 mg' },
  { genericName: 'Ciprofloxacin', form: 'Tablet', strength: '500 mg' },
  { genericName: 'Cotrimoxazole', form: 'Tablet', strength: '800 mg/160 mg' },
  { genericName: 'Metronidazole', brandName: 'Flagyl', form: 'Tablet', strength: '500 mg' },
  { genericName: 'Nitrofurantoin', form: 'Capsule', strength: '100 mg' },
  { genericName: 'Doxycycline', form: 'Capsule', strength: '100 mg' },
  { genericName: 'Cetirizine', brandName: 'Virlix', form: 'Tablet', strength: '10 mg' },
  { genericName: 'Loratadine', brandName: 'Claritin', form: 'Tablet', strength: '10 mg' },
  { genericName: 'Diphenhydramine', form: 'Capsule', strength: '50 mg' },
  { genericName: 'Phenylephrine + Chlorphenamine + Paracetamol', brandName: 'Neozep', form: 'Tablet', strength: '10 mg/2 mg/500 mg' },
  { genericName: 'Carbocisteine', brandName: 'Solmux', form: 'Capsule', strength: '500 mg' },
  { genericName: 'Ambroxol', brandName: 'Mucosolvan', form: 'Tablet', strength: '30 mg' },
  { genericName: 'Salbutamol', brandName: 'Ventolin', form: 'Inhaler', strength: '100 mcg/dose' },
  { genericName: 'Salbutamol', form: 'Nebule', strength: '2.5 mg/2.5 mL' },
  { genericName: 'Budesonide', form: 'Inhaler', strength: '200 mcg/dose' },
  { genericName: 'Montelukast', form: 'Tablet', strength: '10 mg' },
  { genericName: 'Prednisone', form: 'Tablet', strength: '20 mg' },
  { genericName: 'Amlodipine', brandName: 'Norvasc', form: 'Tablet', strength: '5 mg' },
  { genericName: 'Amlodipine', form: 'Tablet', strength: '10 mg' },
  { genericName: 'Losartan', brandName: 'Cozaar', form: 'Tablet', strength: '50 mg' },
  { genericName: 'Losartan + Hydrochlorothiazide', form: 'Tablet', strength: '50 mg/12.5 mg' },
  { genericName: 'Metoprolol Tartrate', form: 'Tablet', strength: '50 mg' },
  { genericName: 'Hydrochlorothiazide', form: 'Tablet', strength: '25 mg' },
  { genericName: 'Atorvastatin', brandName: 'Lipitor', form: 'Tablet', strength: '20 mg' },
  { genericName: 'Rosuvastatin', form: 'Tablet', strength: '10 mg' },
  { genericName: 'Clopidogrel', form: 'Tablet', strength: '75 mg' },
  { genericName: 'Aspirin', form: 'Tablet', strength: '80 mg' },
  { genericName: 'Metformin', brandName: 'Glucophage', form: 'Tablet', strength: '500 mg' },
  { genericName: 'Gliclazide', form: 'Tablet', strength: '80 mg' },
  { genericName: 'Sitagliptin', form: 'Tablet', strength: '100 mg' },
  { genericName: 'Omeprazole', brandName: 'Losec', form: 'Capsule', strength: '20 mg' },
  { genericName: 'Pantoprazole', form: 'Tablet', strength: '40 mg' },
  { genericName: 'Famotidine', form: 'Tablet', strength: '20 mg' },
  { genericName: 'Aluminum Hydroxide + Magnesium Hydroxide', brandName: 'Kremil-S', form: 'Tablet', strength: '178 mg/233 mg' },
  { genericName: 'Loperamide', brandName: 'Diatabs', form: 'Capsule', strength: '2 mg' },
  { genericName: 'Oral Rehydration Salts', form: 'Sachet', strength: '20.5 g' },
  { genericName: 'Domperidone', form: 'Tablet', strength: '10 mg' },
  { genericName: 'Hyoscine N-Butylbromide', brandName: 'Buscopan', form: 'Tablet', strength: '10 mg' },
  { genericName: 'Ferrous Sulfate', form: 'Tablet', strength: '325 mg' },
  { genericName: 'Folic Acid', form: 'Tablet', strength: '5 mg' },
  { genericName: 'Ascorbic Acid', form: 'Tablet', strength: '500 mg' },
  { genericName: 'Multivitamins + Zinc', form: 'Syrup', strength: '120 mL' },
  { genericName: 'Mupirocin', form: 'Ointment', strength: '2%' },
  { genericName: 'Clotrimazole', form: 'Cream', strength: '1%' },
];
